### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by rhysd** [snaka/shiiba#1]
もし下記のプロジェクトと名前が衝突していることを気にしてらっしゃるのでしたら，特に気にする必要は無いと思いますし，一番付けたい名前を付けるのが良いと思います．（用途等も全然違いますし）

https://github.com/rhysd/Shiba

**Comment by rhysd** [comment]
I close this because of no response.

**Comment by snaka** [comment]
このIssue自体気づいてませんでした。わざわざありがとうございます
